name: CI/CD Pipeline

on:
  push:
    branches: [ main, branch-dev ]
  pull_request:
    branches: [ main, branch-dev ]

env:
  DOCKER_IMAGE: carlinhoshk/escola-app
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Instalar Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build with Maven
        run: ./mvnw clean package
        
      - name: Upload JAR 
        uses: actions/upload-artifact@v3
        with:
          name: jar-main
          path: ./target/*.jar

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: ./target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Run Tests
        run: ./mvnw test
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build Docker images e subir serviços
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build -d"
          down-flags: "--volumes"

      - name: Wait for services to be ready
        run: |
          sleep 30
          docker compose ps

      - name: Run Integration Tests
        run: ./mvnw verify

      - name: Push Docker image
        run: |
          docker tag escola-app:latest ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          docker tag escola-app:latest ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          docker push ${{ env.DOCKER_IMAGE }}:latest

